// Copyright (c) Wiesław Šoltés. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using Avalonia.Collections;
using Avalonia.Controls;
using Avalonia.Controls.Primitives;
using Avalonia.Controls.DataGridSorting;
using Avalonia.Data;
using Avalonia.Headless.XUnit;
using Avalonia.Input;
using Avalonia.Markup.Xaml.Styling;
using Avalonia.VisualTree;
using Xunit;

namespace Avalonia.Controls.DataGridTests.Sorting;

public class DataGridSortingHeaderTests
{
    [AvaloniaFact]
    public void Header_Click_Default_Two_State_Cycle_Toggles_Asc_Desc()
    {
        var items = new ObservableCollection<Item>
        {
            new("B"),
            new("A"),
        };

        var grid = CreateGrid(items);

        ClickHeader(grid, "Name");
        grid.UpdateLayout();

        Assert.Equal(new[] { "A", "B" }, GetRowOrder(grid));
        AssertHeaderSort(grid, "Name", asc: true, desc: false);

        ClickHeader(grid, "Name");
        grid.UpdateLayout();

        Assert.Equal(new[] { "B", "A" }, GetRowOrder(grid));
        AssertHeaderSort(grid, "Name", asc: false, desc: true);

        ClickHeader(grid, "Name");
        grid.UpdateLayout();

        Assert.Equal(new[] { "A", "B" }, GetRowOrder(grid));
        AssertHeaderSort(grid, "Name", asc: true, desc: false);

        // Ctrl clears
        ClickHeader(grid, "Name", KeyModifiers.Control);
        grid.UpdateLayout();
        AssertHeaderSort(grid, "Name", asc: false, desc: false);
    }

    [AvaloniaFact]
    public void Header_Click_Two_State_Cycle_Works_In_Observe_Mode()
    {
        var items = new ObservableCollection<Item>
        {
            new("B"),
            new("A"),
        };

        var grid = CreateGrid(items);
        grid.OwnsSortDescriptions = false; // observe mode

        ClickHeader(grid, "Name");
        grid.UpdateLayout();
        Assert.Equal(new[] { "A", "B" }, GetRowOrder(grid));
        AssertHeaderSort(grid, "Name", asc: true, desc: false);

        ClickHeader(grid, "Name");
        grid.UpdateLayout();
        Assert.Equal(new[] { "B", "A" }, GetRowOrder(grid));
        AssertHeaderSort(grid, "Name", asc: false, desc: true);

        // Third click should cycle back to ascending, not clear
        ClickHeader(grid, "Name");
        grid.UpdateLayout();
        Assert.Equal(new[] { "A", "B" }, GetRowOrder(grid));
        AssertHeaderSort(grid, "Name", asc: true, desc: false);
        AssertSingleSort(grid, ListSortDirection.Ascending);
    }

    [AvaloniaFact]
    public void AutoGeneratedColumns_Two_State_Cycle_Shows_Indicator()
    {
        var items = new ObservableCollection<Item>
        {
            new("B", "R1", 2),
            new("A", "R2", 1),
        };

        var grid = CreateAutoGeneratedGrid(items);
        Assert.Equal(SortCycleMode.AscendingDescending, grid.SortCycleMode);

        ClickHeader(grid, "Name");
        grid.UpdateLayout();
        AssertHeaderSort(grid, "Name", asc: true, desc: false);
        AssertSingleSort(grid, ListSortDirection.Ascending);
        Assert.Equal(new[] { "A", "B" }, GetRowOrder(grid));

        ClickHeader(grid, "Name");
        grid.UpdateLayout();
        AssertSingleSort(grid, ListSortDirection.Descending);
        AssertHeaderSort(grid, "Name", asc: false, desc: true);
        Assert.Equal(new[] { "B", "A" }, GetRowOrder(grid));

        ClickHeader(grid, "Name");
        grid.UpdateLayout();
        AssertHeaderSort(grid, "Name", asc: true, desc: false);
        AssertSingleSort(grid, ListSortDirection.Ascending);
        Assert.Equal(new[] { "A", "B" }, GetRowOrder(grid));
    }

    [AvaloniaFact]
    public void Header_Click_With_Shift_Adds_Secondary_Sort()
    {
        var items = new ObservableCollection<Item>
        {
            new("A", "G1", 2),
            new("B", "G2", 1),
            new("C", "G1", 1),
        };

        var grid = CreateGrid(items);

        ClickHeader(grid, "Group");
        ClickHeader(grid, "Value", KeyModifiers.Shift);
        grid.UpdateLayout();

        Assert.Equal(new[] { "C", "A", "B" }, GetRowOrder(grid));
        AssertHeaderSort(grid, "Group", asc: true, desc: false);
        AssertHeaderSort(grid, "Value", asc: true, desc: false);

        var view = (IDataGridCollectionView)grid.ItemsSource!;
        Assert.Equal(2, view.SortDescriptions.Count);
        Assert.Equal("Group", view.SortDescriptions[0].PropertyPath);
        Assert.Equal("Value", view.SortDescriptions[1].PropertyPath);
    }

    private static DataGrid CreateGrid(IEnumerable<Item> items)
    {
        var view = new DataGridCollectionView(items);

        var root = new Window
        {
            Width = 400,
            Height = 300,
            Styles =
            {
                new StyleInclude((Uri?)null)
                {
                    Source = new Uri("avares://Avalonia.Controls.DataGrid/Themes/Simple.xaml")
                },
            }
        };

        var grid = new DataGrid
        {
            ItemsSource = view,
            SelectionMode = DataGridSelectionMode.Extended
        };

        grid.ColumnDefinitions.Add(new DataGridTextColumn
        {
            Header = "Name",
            Binding = new Binding(nameof(Item.Name)),
            SortMemberPath = nameof(Item.Name)
        });
        grid.ColumnDefinitions.Add(new DataGridTextColumn
        {
            Header = "Group",
            Binding = new Binding(nameof(Item.Group)),
            SortMemberPath = nameof(Item.Group)
        });
        grid.ColumnDefinitions.Add(new DataGridTextColumn
        {
            Header = "Value",
            Binding = new Binding(nameof(Item.Value)),
            SortMemberPath = nameof(Item.Value)
        });

        root.Content = grid;
        root.Show();

        grid.UpdateLayout();
        return grid;
    }

    private static DataGrid CreateAutoGeneratedGrid(IEnumerable<Item> items)
    {
        var view = new DataGridCollectionView(items);

        var root = new Window
        {
            Width = 400,
            Height = 300,
            Styles =
            {
                new StyleInclude((Uri?)null)
                {
                    Source = new Uri("avares://Avalonia.Controls.DataGrid/Themes/Simple.xaml")
                },
            }
        };

        var grid = new DataGrid
        {
            AutoGenerateColumns = true,
            ItemsSource = view,
            SelectionMode = DataGridSelectionMode.Extended
        };

        root.Content = grid;
        root.Show();

        grid.UpdateLayout();
        return grid;
    }

    private static void ClickHeader(DataGrid grid, string header, KeyModifiers modifiers = KeyModifiers.None)
    {
        var headerCell = grid.GetVisualDescendants()
            .OfType<DataGridColumnHeader>()
            .First(h => Equals(h.Content, header));

        var method = typeof(DataGridColumnHeader).GetMethod(
            "ProcessSort",
            BindingFlags.Instance | BindingFlags.NonPublic);

        method!.Invoke(headerCell, new object[] { modifiers, null });
    }

    private static void AssertHeaderSort(DataGrid grid, string header, bool asc, bool desc)
    {
        var headerCell = grid.GetVisualDescendants()
            .OfType<DataGridColumnHeader>()
            .First(h => Equals(h.Content, header));

        Assert.Equal(asc, HasPseudo(headerCell, ":sortascending"));
        Assert.Equal(desc, HasPseudo(headerCell, ":sortdescending"));
    }

    private static bool HasPseudo(StyledElement element, string name)
    {
        var prop = typeof(StyledElement).GetProperty("PseudoClasses", BindingFlags.Instance | BindingFlags.NonPublic);
        var pseudo = prop!.GetValue(element);
        var contains = pseudo!.GetType().GetMethod("Contains", new[] { typeof(string) });
        return (bool)contains!.Invoke(pseudo, new object[] { name });
    }

    private static void AssertSingleSort(DataGrid grid, ListSortDirection expected)
    {
        var view = (IDataGridCollectionView)grid.ItemsSource!;
        var sort = Assert.Single(view.SortDescriptions);
        Assert.Equal(expected, sort.Direction);
    }

    private static string[] GetRowOrder(DataGrid grid)
    {
        return ((System.Collections.IEnumerable)grid.ItemsSource!)
            .Cast<Item>()
            .Select(i => i.Name)
            .ToArray();
    }

    private class Item
    {
        public Item(string name, string group = "", int value = 0)
        {
            Name = name;
            Group = group;
            Value = value;
        }

        public string Name { get; }

        public string Group { get; }

        public int Value { get; }
    }
}
