// Copyright (c) Wiesław Šoltés. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

#nullable disable

using System;
using Avalonia.Collections;
using Avalonia.Data;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Layout;
using Avalonia.Media;
using Avalonia.Styling;

namespace Avalonia.Controls
{
    /// <summary>
    /// Represents a <see cref="DataGrid" /> column that hosts <see cref="CalendarDatePicker" /> controls 
    /// for editing date values.
    /// </summary>
#if !DATAGRID_INTERNAL
public
#else
internal
#endif
    class DataGridDatePickerColumn : DataGridBoundColumn
    {
        private readonly Lazy<ControlTheme> _cellDatePickerTheme;
        private readonly Lazy<ControlTheme> _cellTextBlockTheme;

        /// <summary>
        /// Gets the theme applied to <see cref="CalendarDatePicker" /> instances generated by the column.
        /// May return null when no matching resource is found.
        /// </summary>
        protected ControlTheme CellDatePickerTheme => GetThemeValue(_cellDatePickerTheme);

        /// <summary>
        /// Gets the theme applied to display <see cref="TextBlock" /> instances generated by the column.
        /// May return null when no matching resource is found.
        /// </summary>
        protected ControlTheme CellTextBlockTheme => GetThemeValue(_cellTextBlockTheme);

        /// <summary>
        /// Initializes a new instance of the <see cref="DataGridDatePickerColumn"/> class.
        /// </summary>
        public DataGridDatePickerColumn()
        {
            BindingTarget = CalendarDatePicker.SelectedDateProperty;
            _cellDatePickerTheme = new Lazy<ControlTheme>(() => GetColumnControlTheme("DataGridCellDatePickerTheme"));
            _cellTextBlockTheme = new Lazy<ControlTheme>(() => GetColumnControlTheme("DataGridCellDateTextBlockTheme"));
        }

        /// <summary>
        /// Defines the <see cref="DisplayDateStart"/> property.
        /// </summary>
        public static readonly StyledProperty<DateTime?> DisplayDateStartProperty =
            CalendarDatePicker.DisplayDateStartProperty.AddOwner<DataGridDatePickerColumn>();

        /// <summary>
        /// Gets or sets the first date that can be selected.
        /// </summary>
        public DateTime? DisplayDateStart
        {
            get => GetValue(DisplayDateStartProperty);
            set => SetValue(DisplayDateStartProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="DisplayDateEnd"/> property.
        /// </summary>
        public static readonly StyledProperty<DateTime?> DisplayDateEndProperty =
            CalendarDatePicker.DisplayDateEndProperty.AddOwner<DataGridDatePickerColumn>();

        /// <summary>
        /// Gets or sets the last date that can be selected.
        /// </summary>
        public DateTime? DisplayDateEnd
        {
            get => GetValue(DisplayDateEndProperty);
            set => SetValue(DisplayDateEndProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="FirstDayOfWeek"/> property.
        /// </summary>
        public static readonly StyledProperty<DayOfWeek> FirstDayOfWeekProperty =
            CalendarDatePicker.FirstDayOfWeekProperty.AddOwner<DataGridDatePickerColumn>();

        /// <summary>
        /// Gets or sets the first day of the week.
        /// </summary>
        public DayOfWeek FirstDayOfWeek
        {
            get => GetValue(FirstDayOfWeekProperty);
            set => SetValue(FirstDayOfWeekProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="IsTodayHighlighted"/> property.
        /// </summary>
        public static readonly StyledProperty<bool> IsTodayHighlightedProperty =
            CalendarDatePicker.IsTodayHighlightedProperty.AddOwner<DataGridDatePickerColumn>();

        /// <summary>
        /// Gets or sets whether today is highlighted in the calendar.
        /// </summary>
        public bool IsTodayHighlighted
        {
            get => GetValue(IsTodayHighlightedProperty);
            set => SetValue(IsTodayHighlightedProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="SelectedDateFormat"/> property.
        /// </summary>
        public static readonly StyledProperty<CalendarDatePickerFormat> SelectedDateFormatProperty =
            CalendarDatePicker.SelectedDateFormatProperty.AddOwner<DataGridDatePickerColumn>();

        /// <summary>
        /// Gets or sets the date format (Short, Long, or Custom).
        /// </summary>
        public CalendarDatePickerFormat SelectedDateFormat
        {
            get => GetValue(SelectedDateFormatProperty);
            set => SetValue(SelectedDateFormatProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="CustomDateFormatString"/> property.
        /// </summary>
        public static readonly StyledProperty<string> CustomDateFormatStringProperty =
            CalendarDatePicker.CustomDateFormatStringProperty.AddOwner<DataGridDatePickerColumn>();

        /// <summary>
        /// Gets or sets the custom date format string when <see cref="SelectedDateFormat"/> is Custom.
        /// </summary>
        public string CustomDateFormatString
        {
            get => GetValue(CustomDateFormatStringProperty);
            set => SetValue(CustomDateFormatStringProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="Watermark"/> property.
        /// </summary>
        public static readonly StyledProperty<string> WatermarkProperty =
            CalendarDatePicker.WatermarkProperty.AddOwner<DataGridDatePickerColumn>();

        /// <summary>
        /// Gets or sets the placeholder text displayed when no date is selected.
        /// </summary>
        public string Watermark
        {
            get => GetValue(WatermarkProperty);
            set => SetValue(WatermarkProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="HorizontalContentAlignment"/> property.
        /// </summary>
        public static readonly StyledProperty<HorizontalAlignment> HorizontalContentAlignmentProperty =
            ContentControl.HorizontalContentAlignmentProperty.AddOwner<DataGridDatePickerColumn>();

        /// <summary>
        /// Gets or sets the horizontal alignment of the content.
        /// </summary>
        public HorizontalAlignment HorizontalContentAlignment
        {
            get => GetValue(HorizontalContentAlignmentProperty);
            set => SetValue(HorizontalContentAlignmentProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="VerticalContentAlignment"/> property.
        /// </summary>
        public static readonly StyledProperty<VerticalAlignment> VerticalContentAlignmentProperty =
            ContentControl.VerticalContentAlignmentProperty.AddOwner<DataGridDatePickerColumn>();

        /// <summary>
        /// Gets or sets the vertical alignment of the content.
        /// </summary>
        public VerticalAlignment VerticalContentAlignment
        {
            get => GetValue(VerticalContentAlignmentProperty);
            set => SetValue(VerticalContentAlignmentProperty, value);
        }

        static DataGridDatePickerColumn()
        {
            IsTodayHighlightedProperty.OverrideDefaultValue<DataGridDatePickerColumn>(true);
            SelectedDateFormatProperty.OverrideDefaultValue<DataGridDatePickerColumn>(CalendarDatePickerFormat.Short);
        }

        /// <summary>
        /// Notifies the DataGrid when a property changes.
        /// </summary>
        protected override void OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
        {
            base.OnPropertyChanged(change);

            if (change.Property == DisplayDateStartProperty
                || change.Property == DisplayDateEndProperty
                || change.Property == FirstDayOfWeekProperty
                || change.Property == IsTodayHighlightedProperty
                || change.Property == SelectedDateFormatProperty
                || change.Property == CustomDateFormatStringProperty
                || change.Property == WatermarkProperty
                || change.Property == HorizontalContentAlignmentProperty
                || change.Property == VerticalContentAlignmentProperty)
            {
                NotifyPropertyChanged(change.Property.Name);
            }
        }

        /// <summary>
        /// Causes the column cell being edited to revert to the specified value.
        /// </summary>
        protected override void CancelCellEdit(Control editingElement, object uneditedValue)
        {
            if (editingElement is CalendarDatePicker datePicker)
            {
                datePicker.SelectedDate = uneditedValue as DateTime?;
            }
        }

        /// <summary>
        /// Creates the visual tree for read-only cells.
        /// </summary>
        protected override Control GenerateElement(DataGridCell cell, object dataItem)
        {
            var textBlock = new TextBlock
            {
                Name = "CellDateTextBlock",
                VerticalAlignment = VerticalAlignment.Center
            };

            if (CellTextBlockTheme is { } theme)
            {
                textBlock.Theme = theme;
            }

            SyncDisplayAlignment(textBlock);

            if (Binding != null && dataItem != DataGridCollectionView.NewItemPlaceholder)
            {
                // Create a binding with format string based on SelectedDateFormat
                string formatString = GetDateFormatString();
                
                if (Binding is Binding binding)
                {
                    var displayBinding = new Binding
                    {
                        Path = binding.Path,
                        Mode = BindingMode.OneWay,
                        StringFormat = formatString,
                        Converter = binding.Converter,
                        ConverterParameter = binding.ConverterParameter
                    };
                    textBlock.Bind(TextBlock.TextProperty, displayBinding);
                }
                else
                {
                    textBlock.Bind(TextBlock.TextProperty, Binding);
                }
            }

            return textBlock;
        }

        /// <summary>
        /// Creates the visual tree for editing cells.
        /// </summary>
        protected override Control GenerateEditingElementDirect(DataGridCell cell, object dataItem)
        {
            var datePicker = new CalendarDatePicker
            {
                Name = "CellDatePicker",
                HorizontalAlignment = HorizontalAlignment.Stretch,
                VerticalAlignment = VerticalAlignment.Center
            };

            if (CellDatePickerTheme is { } theme)
            {
                datePicker.Theme = theme;
            }

            SyncEditProperties(datePicker);

            return datePicker;
        }

        /// <summary>
        /// Called when a cell in the column enters editing mode.
        /// </summary>
        protected override object PrepareCellForEdit(Control editingElement, RoutedEventArgs editingEventArgs)
        {
            if (editingElement is CalendarDatePicker datePicker)
            {
                var uneditedValue = datePicker.SelectedDate;
                
                // Focus the date picker
                datePicker.Focus();

                return uneditedValue;
            }

            return null;
        }

        /// <summary>
        /// Called by the DataGrid control when this column asks for its elements to be updated.
        /// </summary>
        protected internal override void RefreshCellContent(Control element, string propertyName)
        {
            if (element == null)
            {
                throw new ArgumentNullException(nameof(element));
            }

            if (element is CalendarDatePicker datePicker)
            {
                SyncEditProperties(datePicker);
            }
            else if (element is TextBlock textBlock)
            {
                if (propertyName == nameof(HorizontalContentAlignment) ||
                    propertyName == nameof(VerticalContentAlignment))
                {
                    SyncDisplayAlignment(textBlock);
                }
                else
                {
                    base.RefreshCellContent(element, propertyName);
                }
            }
            else
            {
                base.RefreshCellContent(element, propertyName);
            }
        }

        private string GetDateFormatString()
        {
            return SelectedDateFormat switch
            {
                CalendarDatePickerFormat.Long => "D",
                CalendarDatePickerFormat.Custom when !string.IsNullOrEmpty(CustomDateFormatString) => CustomDateFormatString,
                _ => "d" // Short format
            };
        }

        private void SyncEditProperties(CalendarDatePicker datePicker)
        {
            if (DisplayDateStart.HasValue)
            {
                datePicker.DisplayDateStart = DisplayDateStart;
            }

            if (DisplayDateEnd.HasValue)
            {
                datePicker.DisplayDateEnd = DisplayDateEnd;
            }

            datePicker.FirstDayOfWeek = FirstDayOfWeek;
            datePicker.IsTodayHighlighted = IsTodayHighlighted;
            datePicker.SelectedDateFormat = SelectedDateFormat;

            if (!string.IsNullOrEmpty(CustomDateFormatString))
            {
                datePicker.CustomDateFormatString = CustomDateFormatString;
            }

            if (!string.IsNullOrEmpty(Watermark))
            {
                datePicker.Watermark = Watermark;
            }

            DataGridHelper.SyncColumnProperty(this, datePicker, HorizontalContentAlignmentProperty);
            DataGridHelper.SyncColumnProperty(this, datePicker, VerticalContentAlignmentProperty);
        }

        private void SyncDisplayAlignment(TextBlock textBlock)
        {
            if (IsSet(HorizontalContentAlignmentProperty))
            {
                textBlock.TextAlignment = HorizontalContentAlignment switch
                {
                    HorizontalAlignment.Left => TextAlignment.Left,
                    HorizontalAlignment.Center => TextAlignment.Center,
                    HorizontalAlignment.Right => TextAlignment.Right,
                    _ => TextAlignment.Left
                };
            }
            else
            {
                textBlock.ClearValue(TextBlock.TextAlignmentProperty);
            }

            textBlock.VerticalAlignment = IsSet(VerticalContentAlignmentProperty)
                ? VerticalContentAlignment
                : VerticalAlignment.Center;
        }

        private ControlTheme GetThemeValue(Lazy<ControlTheme> themeCache)
        {
            if (themeCache.IsValueCreated)
            {
                return themeCache.Value;
            }

            // Avoid permanently caching null before the column is attached to a grid.
            return OwningGrid == null ? null : themeCache.Value;
        }
    }
}
