// Copyright (c) Wiesław Šoltés. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

#nullable disable

using System;
using Avalonia.Collections;
using Avalonia.Controls.Primitives;
using Avalonia.Data;
using Avalonia.Interactivity;
using Avalonia.Layout;
using Avalonia.Media;
using Avalonia.Styling;

namespace Avalonia.Controls
{
    /// <summary>
    /// Represents a <see cref="DataGrid" /> column that hosts <see cref="ProgressBar" /> controls 
    /// for displaying progress values. This column is read-only.
    /// </summary>
#if !DATAGRID_INTERNAL
public
#else
internal
#endif
    class DataGridProgressBarColumn : DataGridBoundColumn
    {
        private readonly Lazy<ControlTheme> _cellProgressBarTheme;

        /// <summary>
        /// Gets the theme applied to <see cref="ProgressBar" /> instances generated by the column.
        /// May return null when no matching resource is found.
        /// </summary>
        protected ControlTheme CellProgressBarTheme => GetThemeValue(_cellProgressBarTheme);

        /// <summary>
        /// Initializes a new instance of the <see cref="DataGridProgressBarColumn"/> class.
        /// </summary>
        public DataGridProgressBarColumn()
        {
            BindingTarget = ProgressBar.ValueProperty;
            _cellProgressBarTheme = new Lazy<ControlTheme>(() => GetColumnControlTheme("DataGridCellProgressBarTheme"));
        }

        /// <summary>
        /// Defines the <see cref="Minimum"/> property.
        /// </summary>
        public static readonly StyledProperty<double> MinimumProperty =
            RangeBase.MinimumProperty.AddOwner<DataGridProgressBarColumn>();

        /// <summary>
        /// Gets or sets the minimum value.
        /// </summary>
        public double Minimum
        {
            get => GetValue(MinimumProperty);
            set => SetValue(MinimumProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="Maximum"/> property.
        /// </summary>
        public static readonly StyledProperty<double> MaximumProperty =
            RangeBase.MaximumProperty.AddOwner<DataGridProgressBarColumn>();

        /// <summary>
        /// Gets or sets the maximum value.
        /// </summary>
        public double Maximum
        {
            get => GetValue(MaximumProperty);
            set => SetValue(MaximumProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="ShowProgressText"/> property.
        /// </summary>
        public static readonly StyledProperty<bool> ShowProgressTextProperty =
            ProgressBar.ShowProgressTextProperty.AddOwner<DataGridProgressBarColumn>();

        /// <summary>
        /// Gets or sets whether to show progress text.
        /// </summary>
        public bool ShowProgressText
        {
            get => GetValue(ShowProgressTextProperty);
            set => SetValue(ShowProgressTextProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="ProgressTextFormat"/> property.
        /// </summary>
        public static readonly StyledProperty<string> ProgressTextFormatProperty =
            ProgressBar.ProgressTextFormatProperty.AddOwner<DataGridProgressBarColumn>();

        /// <summary>
        /// Gets or sets the progress text format.
        /// </summary>
        public string ProgressTextFormat
        {
            get => GetValue(ProgressTextFormatProperty);
            set => SetValue(ProgressTextFormatProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="Foreground"/> property.
        /// </summary>
        public static readonly StyledProperty<IBrush> ForegroundProperty =
            TemplatedControl.ForegroundProperty.AddOwner<DataGridProgressBarColumn>();

        /// <summary>
        /// Gets or sets the progress bar foreground color.
        /// </summary>
        public IBrush Foreground
        {
            get => GetValue(ForegroundProperty);
            set => SetValue(ForegroundProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="Background"/> property.
        /// </summary>
        public static readonly StyledProperty<IBrush> BackgroundProperty =
            TemplatedControl.BackgroundProperty.AddOwner<DataGridProgressBarColumn>();

        /// <summary>
        /// Gets or sets the progress bar background color.
        /// </summary>
        public IBrush Background
        {
            get => GetValue(BackgroundProperty);
            set => SetValue(BackgroundProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="Height"/> property.
        /// </summary>
        public static readonly StyledProperty<double> HeightProperty =
            AvaloniaProperty.Register<DataGridProgressBarColumn, double>(nameof(Height), double.NaN);

        /// <summary>
        /// Gets or sets the progress bar height.
        /// </summary>
        public double Height
        {
            get => GetValue(HeightProperty);
            set => SetValue(HeightProperty, value);
        }

        static DataGridProgressBarColumn()
        {
            MinimumProperty.OverrideDefaultValue<DataGridProgressBarColumn>(0);
            MaximumProperty.OverrideDefaultValue<DataGridProgressBarColumn>(100);
            ShowProgressTextProperty.OverrideDefaultValue<DataGridProgressBarColumn>(false);
            ProgressTextFormatProperty.OverrideDefaultValue<DataGridProgressBarColumn>("{1:0}%");
        }

        /// <summary>
        /// Gets or sets whether this column is read-only. Always returns true for progress bar columns.
        /// </summary>
        public override bool IsReadOnly
        {
            get => true;
            set { } // Ignore - progress bar columns are always read-only
        }

        /// <summary>
        /// Notifies the DataGrid when a property changes.
        /// </summary>
        protected override void OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
        {
            base.OnPropertyChanged(change);

            if (change.Property == MinimumProperty
                || change.Property == MaximumProperty
                || change.Property == ShowProgressTextProperty
                || change.Property == ProgressTextFormatProperty
                || change.Property == ForegroundProperty
                || change.Property == BackgroundProperty
                || change.Property == HeightProperty)
            {
                NotifyPropertyChanged(change.Property.Name);
            }
        }

        /// <summary>
        /// Not supported for read-only columns.
        /// </summary>
        protected override void CancelCellEdit(Control editingElement, object uneditedValue)
        {
            // Progress bar is read-only, nothing to cancel
        }

        /// <summary>
        /// Creates the visual tree for cells.
        /// </summary>
        protected override Control GenerateElement(DataGridCell cell, object dataItem)
        {
            var progressBar = new ProgressBar
            {
                Name = "CellProgressBar",
                VerticalAlignment = VerticalAlignment.Center,
                HorizontalAlignment = HorizontalAlignment.Stretch
            };

            if (CellProgressBarTheme is { } theme)
            {
                progressBar.Theme = theme;
            }

            SyncProgressBarProperties(progressBar);

            if (Binding != null && dataItem != DataGridCollectionView.NewItemPlaceholder)
            {
                progressBar.Bind(ProgressBar.ValueProperty, Binding);
            }

            return progressBar;
        }

        /// <summary>
        /// Progress bar columns do not support editing - returns the display element.
        /// </summary>
        protected override Control GenerateEditingElementDirect(DataGridCell cell, object dataItem)
        {
            // Return display element since this column is read-only
            return GenerateElement(cell, dataItem);
        }

        /// <summary>
        /// Not supported for read-only columns.
        /// </summary>
        protected override object PrepareCellForEdit(Control editingElement, RoutedEventArgs editingEventArgs)
        {
            return null;
        }

        /// <summary>
        /// Called by the DataGrid control when this column asks for its elements to be updated.
        /// </summary>
        protected internal override void RefreshCellContent(Control element, string propertyName)
        {
            if (element == null)
            {
                throw new ArgumentNullException(nameof(element));
            }

            if (element is ProgressBar progressBar)
            {
                SyncProgressBarProperties(progressBar);
            }
            else
            {
                base.RefreshCellContent(element, propertyName);
            }
        }

        private void SyncProgressBarProperties(ProgressBar progressBar)
        {
            progressBar.Minimum = Minimum;
            progressBar.Maximum = Maximum;
            progressBar.ShowProgressText = ShowProgressText;
            progressBar.ProgressTextFormat = ProgressTextFormat;

            if (Foreground != null)
            {
                progressBar.Foreground = Foreground;
            }

            if (Background != null)
            {
                progressBar.Background = Background;
            }

            if (!double.IsNaN(Height))
            {
                progressBar.Height = Height;
            }
        }

        private ControlTheme GetThemeValue(Lazy<ControlTheme> themeCache)
        {
            if (themeCache.IsValueCreated)
            {
                return themeCache.Value;
            }

            // Avoid permanently caching null before the column is attached to a grid.
            return OwningGrid == null ? null : themeCache.Value;
        }
    }
}
