// This source is subject to the Microsoft Public License (Ms-PL).
// Please see http://go.microsoft.com/fwlink/?LinkID=131993 for details.
// All other rights reserved.

#nullable disable

using Avalonia;
using Avalonia.Threading;
using System;
using System.Collections.ObjectModel;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;

namespace Avalonia.Controls
{
#if !DATAGRID_INTERNAL
public
#else
internal
#endif
    partial class DataGrid
    {
        private void SetColumnsBindingValue(IList<DataGridColumn> value)
        {
            if (_areHandlersSuspended)
            {
                return;
            }

            if (ReferenceEquals(value, ColumnsInternal))
            {
                return;
            }

            SetAndRaise(ColumnsProperty, ref _boundColumns, value);
        }

        private void OnColumnsPropertyChanged(AvaloniaPropertyChangedEventArgs e)
        {
            if (_areHandlersSuspended)
            {
                return;
            }

            var oldValue = (IList<DataGridColumn>)e.OldValue;
            var newValue = (IList<DataGridColumn>)e.NewValue;

            if (ReferenceEquals(oldValue, newValue))
            {
                return;
            }

            DetachBoundColumns(oldValue);

            if (newValue == null)
            {
                _pendingBoundColumnsApply = false;
                ClearColumnsForBinding();
                _boundColumnsList = null;
                return;
            }

            _boundColumnsList = newValue as IList<DataGridColumn>;

            try
            {
                if (_columnDefinitionsSource != null)
                {
                    throw new InvalidOperationException("Cannot bind Columns when ColumnDefinitionsSource is already defined. Clear ColumnDefinitionsSource before binding Columns.");
                }

                if (HasInlineColumnsDefined())
                {
                    throw new InvalidOperationException("Cannot bind Columns when inline columns are already defined. Clear existing columns before binding.");
                }

                AttachBoundColumns(newValue);

                if (_autoGeneratingColumnOperationCount > 0)
                {
                    _pendingBoundColumnsApply = true;
                    return;
                }

                ApplyBoundColumnsSnapshot();
            }
            catch
            {
                // roll back the bound collection on failure
                _boundColumns = oldValue;
                _boundColumnsList = oldValue as IList<DataGridColumn>;
                AttachBoundColumns(oldValue);
                throw;
            }
        }

        private void OnColumnsSynchronizationModeChanged(AvaloniaPropertyChangedEventArgs e)
        {
            if (_areHandlersSuspended)
            {
                return;
            }

            if (_boundColumns != null)
            {
                _twoWayColumnsAvailable =
                    ColumnsSynchronizationMode == ColumnsSynchronizationMode.TwoWay &&
                    _boundColumnsList != null &&
                    _boundColumnsNotifications != null;

                if (ColumnsSynchronizationMode == ColumnsSynchronizationMode.TwoWay && !_twoWayColumnsAvailable)
                {
                    System.Diagnostics.Debug.WriteLine("TwoWay Columns synchronization requires IList + INotifyCollectionChanged; falling back to OneWayToGrid behavior.");
                }

                // Re-sync to respect new mode.
                ApplyBoundColumnsSnapshot();
            }
        }

        private void OnColumnsSourceResetBehaviorChanged(AvaloniaPropertyChangedEventArgs e)
        {
            if (_areHandlersSuspended)
            {
                return;
            }

            // No immediate action required; behavior is applied on Reset notifications.
        }

        private void OnAutoGeneratedColumnsPlacementChanged(AvaloniaPropertyChangedEventArgs e)
        {
            if (_areHandlersSuspended)
            {
                return;
            }

            if (HasColumnsSource())
            {
                ApplyAutoGeneratedColumnsPlacement();
            }
        }

        private void AttachBoundColumns(IList<DataGridColumn> collection)
        {
            _boundColumnsList = collection as IList<DataGridColumn>;
            _boundColumnsNotifications = collection as INotifyCollectionChanged;
            if (_boundColumnsNotifications != null)
            {
                _boundColumnsNotifications.CollectionChanged += BoundColumns_CollectionChanged;
            }
            else
            {
                System.Diagnostics.Debug.WriteLine("Columns source does not implement INotifyCollectionChanged; applying snapshot without live updates.");
            }
            _boundColumnsThreadId = Environment.CurrentManagedThreadId;

            _twoWayColumnsAvailable =
                ColumnsSynchronizationMode == ColumnsSynchronizationMode.TwoWay &&
                _boundColumnsList != null &&
                _boundColumnsNotifications != null;

            if (ColumnsSynchronizationMode == ColumnsSynchronizationMode.TwoWay && !_twoWayColumnsAvailable)
            {
                System.Diagnostics.Debug.WriteLine("TwoWay Columns synchronization requires IList + INotifyCollectionChanged; falling back to OneWayToGrid behavior.");
            }
        }

        private void DetachBoundColumns(IList<DataGridColumn> collection)
        {
            if (_boundColumnsNotifications != null && collection != null)
            {
                _boundColumnsNotifications.CollectionChanged -= BoundColumns_CollectionChanged;
            }

            _boundColumnsNotifications = null;
            _twoWayColumnsAvailable = false;
            _boundColumnsThreadId = null;
            _boundColumnsList = null;
        }

        private void BoundColumns_CollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (!Dispatcher.UIThread.CheckAccess())
            {
                throw new InvalidOperationException("Columns changes must occur on the UI thread.");
            }

            if (_boundColumnsThreadId.HasValue && _boundColumnsThreadId.Value != Environment.CurrentManagedThreadId)
            {
                throw new InvalidOperationException("Columns changes must occur on the same thread that created the binding.");
            }

            if (_syncingInternalColumns)
            {
                return;
            }

            _syncingBoundColumns = true;
            var updateDisplayIndexes = false;
            try
            {
                switch (e.Action)
                {
                    case NotifyCollectionChangedAction.Add:
                        AddBoundColumns(e);
                        updateDisplayIndexes = true;
                        break;
                    case NotifyCollectionChangedAction.Remove:
                        RemoveBoundColumns(e);
                        updateDisplayIndexes = true;
                        break;
                    case NotifyCollectionChangedAction.Replace:
                        ReplaceBoundColumns(e);
                        updateDisplayIndexes = true;
                        break;
                    case NotifyCollectionChangedAction.Move:
                        MoveBoundColumns(e);
                        updateDisplayIndexes = true;
                        break;
                    case NotifyCollectionChangedAction.Reset:
                        if (ColumnsSourceResetBehavior != ColumnsSourceResetBehavior.Ignore)
                        {
                            HandleBoundReset();
                            updateDisplayIndexes = true;
                        }
                        break;
                }

                if (updateDisplayIndexes)
                {
                    ApplyBoundDisplayIndexes();
                }
            }
            finally
            {
                _syncingBoundColumns = false;
            }
        }

        private void AddBoundColumns(NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems == null)
            {
                return;
            }

            var insertIndex = GetBoundInsertIndex(e.NewStartingIndex);
            foreach (DataGridColumn column in e.NewItems)
            {
                ValidateBoundColumn(column);
                ColumnsInternal.Insert(insertIndex++, column);
            }

            ApplyAutoGeneratedColumnsPlacement();
        }

        private void RemoveBoundColumns(NotifyCollectionChangedEventArgs e)
        {
            if (e.OldItems == null)
            {
                return;
            }

            for (int i = 0; i < e.OldItems.Count; i++)
            {
                var column = (DataGridColumn)e.OldItems[i];
                var index = ColumnsInternal.IndexOf(column);
                if (index >= 0)
                {
                    ColumnsInternal.RemoveAt(index);
                }
            }
        }

        private void ReplaceBoundColumns(NotifyCollectionChangedEventArgs e)
        {
            RemoveBoundColumns(e);
            if (e.NewItems == null)
            {
                return;
            }

            var insertIndex = GetBoundInsertIndex(e.NewStartingIndex);
            foreach (DataGridColumn column in e.NewItems)
            {
                ValidateBoundColumn(column);
                ColumnsInternal.Insert(insertIndex++, column);
            }
        }

        private void MoveBoundColumns(NotifyCollectionChangedEventArgs e)
        {
            if (e.OldItems == null || e.OldItems.Count == 0)
            {
                return;
            }
            ApplyBoundColumnsSnapshot();
        }

        private void HandleBoundReset()
        {
            if (ColumnsSourceResetBehavior == ColumnsSourceResetBehavior.Ignore)
            {
                return;
            }

            ApplyBoundColumnsSnapshot();
        }

        private int GetBoundInsertIndex(int boundIndex)
        {
            var autoCount = ColumnsInternal.Count(c => c.IsAutoGenerated);
            return AutoGeneratedColumnsPlacement == AutoGeneratedColumnsPlacement.BeforeSource
                ? autoCount + boundIndex
                : boundIndex;
        }

        private void ApplyBoundColumnsSnapshot()
        {
            if (_boundColumns == null)
            {
                return;
            }

            List<DataGridColumn> snapshot;
            try
            {
                snapshot = _boundColumns.ToList();
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"Failed to enumerate bound Columns: {ex}");
                throw new InvalidOperationException("Failed to enumerate bound Columns.", ex);
            }

            _areHandlersSuspended = true;
            _syncingBoundColumns = true;
            try
            {
                var autoColumns = ColumnsInternal.Where(c => c.IsAutoGenerated).ToList();
                ClearColumnsForBinding();

                if (AutoGeneratedColumnsPlacement == AutoGeneratedColumnsPlacement.BeforeSource)
                {
                    foreach (var auto in autoColumns)
                    {
                        ColumnsInternal.Add(auto);
                    }
                }

                foreach (var column in snapshot)
                {
                    ValidateBoundColumn(column);
                    ColumnsInternal.Add(column);
                }

                if (AutoGeneratedColumnsPlacement == AutoGeneratedColumnsPlacement.AfterSource)
                {
                    foreach (var auto in autoColumns)
                    {
                        ColumnsInternal.Add(auto);
                    }
                }
                ApplyBoundDisplayIndexes();
            }
            finally
            {
                _syncingBoundColumns = false;
                _areHandlersSuspended = false;
            }
        }

        private void ApplyAutoGeneratedColumnsPlacement()
        {
            if (_boundColumns == null && _columnDefinitionsSource == null)
            {
                return;
            }

            if (AutoGeneratedColumnsPlacement == AutoGeneratedColumnsPlacement.None)
            {
                RemoveAutoGeneratedColumns();
                return;
            }

            if (_boundColumns != null)
            {
                if (AutoGeneratedColumnsPlacement == AutoGeneratedColumnsPlacement.BeforeSource)
                {
                    var auto = ColumnsInternal.Where(c => c.IsAutoGenerated).ToList();
                    var manual = ColumnsInternal.Where(c => !c.IsAutoGenerated && c is not DataGridFillerColumn).ToList();
                    _areHandlersSuspended = true;
                    _syncingBoundColumns = true;
                    try
                    {
                        ClearColumnsForBinding();
                        foreach (var a in auto)
                        {
                            ColumnsInternal.Add(a);
                        }
                        foreach (var m in manual)
                        {
                            ColumnsInternal.Add(m);
                        }
                    }
                    finally
                    {
                        _syncingBoundColumns = false;
                        _areHandlersSuspended = false;
                    }
                }
                return;
            }

            if (_columnDefinitionsSource != null)
            {
                ApplyColumnDefinitionsSnapshot();
            }
        }

        private void ApplyPendingBoundColumns()
        {
            if (!_pendingBoundColumnsApply)
            {
                return;
            }

            _pendingBoundColumnsApply = false;
            ApplyBoundColumnsSnapshot();
        }

        private void ApplyBoundDisplayIndexes()
        {
            if (_boundColumns == null)
            {
                return;
            }

            _areHandlersSuspended = true;
            try
            {
                var autoColumns = ColumnsInternal.Where(c => c.IsAutoGenerated).ToList();
                var displayIndex = 0;

                if (AutoGeneratedColumnsPlacement == AutoGeneratedColumnsPlacement.BeforeSource)
                {
                    foreach (var auto in autoColumns)
                    {
                        auto.DisplayIndex = displayIndex++;
                    }
                }

                foreach (var column in _boundColumns)
                {
                    if (column != null && ColumnsInternal.Contains(column))
                    {
                        column.DisplayIndex = displayIndex++;
                    }
                }

                if (AutoGeneratedColumnsPlacement == AutoGeneratedColumnsPlacement.AfterSource)
                {
                    foreach (var auto in autoColumns)
                    {
                        auto.DisplayIndex = displayIndex++;
                    }
                }
            }
            finally
            {
                _areHandlersSuspended = false;
            }
        }

        private void ValidateBoundColumn(DataGridColumn column)
        {
            if (column == null)
            {
                throw new ArgumentNullException(nameof(column));
            }

            if (column is DataGridFillerColumn)
            {
                throw new ArgumentException("Cannot bind filler or spacer columns.", nameof(column));
            }

            if (column.OwningGrid != null && column.OwningGrid != this)
            {
                throw new InvalidOperationException("Column already belongs to another DataGrid. Detach it before binding.");
            }
        }

        private void ClearColumnsForBinding()
        {
            _areHandlersSuspended = true;
            try
            {
                for (int i = ColumnsInternal.Count - 1; i >= 0; i--)
                {
                    if (ColumnsInternal[i] is DataGridFillerColumn)
                    {
                        continue;
                    }
                    ColumnsInternal.RemoveAt(i);
                }
            }
            finally
            {
                _areHandlersSuspended = false;
            }
        }

        private bool HasInlineColumnsDefined()
        {
            return ColumnsInternal.Any(c =>
                !c.IsAutoGenerated &&
                c is not DataGridFillerColumn &&
                (_boundColumns == null || !_boundColumns.Contains(c)));
        }

        private void OnColumnDisplayIndexChangedBinding(DataGridColumnEventArgs e)
        {
            if (_boundColumns == null || !_twoWayColumnsAvailable)
            {
                return;
            }

            if (_syncingBoundColumns)
            {
                return;
            }

            if (_boundColumnsList == null)
            {
                return;
            }

            _syncingInternalColumns = true;
            try
            {
                var ordered = ColumnsInternal.Where(ShouldSyncToBound)
                    .OrderBy(c => c.DisplayIndex)
                    .ToList();

                for (int i = 0; i < ordered.Count; i++)
                {
                    var column = ordered[i];
                    var currentIndex = _boundColumnsList.IndexOf(column);
                    if (currentIndex != i && currentIndex >= 0)
                    {
                        _boundColumnsList.RemoveAt(currentIndex);
                        _boundColumnsList.Insert(Math.Min(i, _boundColumnsList.Count), column);
                    }
                }
            }
            finally
            {
                _syncingInternalColumns = false;
            }
        }

        private void OnColumnsInternalBindingChanged(NotifyCollectionChangedEventArgs e)
        {
            if (_boundColumns == null || !_twoWayColumnsAvailable)
            {
                return;
            }

            if (_syncingBoundColumns)
            {
                return;
            }

            if (_boundColumnsList == null)
            {
                return;
            }

            _syncingInternalColumns = true;
            try
            {
                switch (e.Action)
                {
                    case NotifyCollectionChangedAction.Add:
                        if (e.NewItems != null)
                        {
                            var insertIndex = Math.Min(e.NewStartingIndex, _boundColumnsList.Count);
                            foreach (DataGridColumn column in e.NewItems)
                            {
                                if (ShouldSyncToBound(column))
                                {
                                    _boundColumnsList.Insert(insertIndex++, column);
                                }
                            }
                        }
                        break;
                    case NotifyCollectionChangedAction.Remove:
                        if (e.OldItems != null)
                        {
                            foreach (DataGridColumn column in e.OldItems)
                            {
                                if (ShouldSyncToBound(column))
                                {
                                    _boundColumnsList.Remove(column);
                                }
                            }
                        }
                        break;
                    case NotifyCollectionChangedAction.Replace:
                        if (e.OldItems != null)
                        {
                            foreach (DataGridColumn column in e.OldItems)
                            {
                                if (ShouldSyncToBound(column))
                                {
                                    _boundColumnsList.Remove(column);
                                }
                            }
                        }
                        if (e.NewItems != null)
                        {
                            var insertIndex = Math.Min(e.NewStartingIndex, _boundColumnsList.Count);
                            foreach (DataGridColumn column in e.NewItems)
                            {
                                if (ShouldSyncToBound(column))
                                {
                                    _boundColumnsList.Insert(insertIndex++, column);
                                }
                            }
                        }
                        break;
                    case NotifyCollectionChangedAction.Move:
                        if (e.OldItems != null && e.OldItems.Count == 1)
                        {
                            var column = (DataGridColumn)e.OldItems[0];
                            if (ShouldSyncToBound(column))
                            {
                                var oldIndex = _boundColumnsList.IndexOf(column);
                                var newIndex = Math.Min(e.NewStartingIndex, _boundColumnsList.Count - 1);
                                if (oldIndex >= 0 && newIndex >= 0 && oldIndex != newIndex)
                                {
                                    _boundColumnsList.RemoveAt(oldIndex);
                                    _boundColumnsList.Insert(newIndex, column);
                                }
                            }
                        }
                        break;
                    case NotifyCollectionChangedAction.Reset:
                        _boundColumnsList.Clear();
                        break;
                }
            }
            finally
            {
                _syncingInternalColumns = false;
            }
        }

        private bool ShouldSyncToBound(DataGridColumn column)
        {
            return column != null && !column.IsAutoGenerated && column is not DataGridFillerColumn;
        }
    }
}
