// Copyright (c) Wiesław Šoltés. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

#nullable disable

using System;
using System.Collections;
using Avalonia.Collections;
using Avalonia.Controls.Templates;
using Avalonia.Data;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Layout;
using Avalonia.Styling;

namespace Avalonia.Controls
{
    /// <summary>
    /// Represents a <see cref="DataGrid" /> column that hosts <see cref="AutoCompleteBox" /> controls 
    /// for editing text values with auto-completion support.
    /// </summary>
#if !DATAGRID_INTERNAL
public
#else
internal
#endif
    class DataGridAutoCompleteColumn : DataGridBoundColumn
    {
        private readonly Lazy<ControlTheme> _cellAutoCompleteTheme;
        private readonly Lazy<ControlTheme> _cellTextBlockTheme;

        /// <summary>
        /// Gets the theme applied to <see cref="AutoCompleteBox" /> instances generated by the column.
        /// May return null when no matching resource is found.
        /// </summary>
        protected ControlTheme CellAutoCompleteTheme => GetThemeValue(_cellAutoCompleteTheme);

        /// <summary>
        /// Gets the theme applied to display <see cref="TextBlock" /> instances generated by the column.
        /// May return null when no matching resource is found.
        /// </summary>
        protected ControlTheme CellTextBlockTheme => GetThemeValue(_cellTextBlockTheme);

        /// <summary>
        /// Initializes a new instance of the <see cref="DataGridAutoCompleteColumn"/> class.
        /// </summary>
        public DataGridAutoCompleteColumn()
        {
            BindingTarget = AutoCompleteBox.TextProperty;
            _cellAutoCompleteTheme = new Lazy<ControlTheme>(() => GetColumnControlTheme("DataGridCellAutoCompleteBoxTheme"));
            _cellTextBlockTheme = new Lazy<ControlTheme>(() => GetColumnControlTheme("DataGridCellAutoCompleteTextBlockTheme"));
        }

        /// <summary>
        /// Defines the <see cref="ItemsSource"/> property.
        /// </summary>
        public static readonly StyledProperty<IEnumerable> ItemsSourceProperty =
            AutoCompleteBox.ItemsSourceProperty.AddOwner<DataGridAutoCompleteColumn>();

        /// <summary>
        /// Gets or sets the items source for auto-complete suggestions.
        /// </summary>
        public IEnumerable ItemsSource
        {
            get => GetValue(ItemsSourceProperty);
            set => SetValue(ItemsSourceProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="ItemTemplate"/> property.
        /// </summary>
        public static readonly StyledProperty<IDataTemplate> ItemTemplateProperty =
            AutoCompleteBox.ItemTemplateProperty.AddOwner<DataGridAutoCompleteColumn>();

        /// <summary>
        /// Gets or sets the template used to display each item in the suggestion list.
        /// </summary>
        public IDataTemplate ItemTemplate
        {
            get => GetValue(ItemTemplateProperty);
            set => SetValue(ItemTemplateProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="FilterMode"/> property.
        /// </summary>
        public static readonly StyledProperty<AutoCompleteFilterMode> FilterModeProperty =
            AutoCompleteBox.FilterModeProperty.AddOwner<DataGridAutoCompleteColumn>();

        /// <summary>
        /// Gets or sets the filter mode used for filtering suggestions.
        /// </summary>
        public AutoCompleteFilterMode FilterMode
        {
            get => GetValue(FilterModeProperty);
            set => SetValue(FilterModeProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="MinimumPrefixLength"/> property.
        /// </summary>
        public static readonly StyledProperty<int> MinimumPrefixLengthProperty =
            AutoCompleteBox.MinimumPrefixLengthProperty.AddOwner<DataGridAutoCompleteColumn>();

        /// <summary>
        /// Gets or sets the minimum number of characters required before suggestions appear.
        /// </summary>
        public int MinimumPrefixLength
        {
            get => GetValue(MinimumPrefixLengthProperty);
            set => SetValue(MinimumPrefixLengthProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="MinimumPopulateDelay"/> property.
        /// </summary>
        public static readonly StyledProperty<TimeSpan> MinimumPopulateDelayProperty =
            AutoCompleteBox.MinimumPopulateDelayProperty.AddOwner<DataGridAutoCompleteColumn>();

        /// <summary>
        /// Gets or sets the minimum delay before population occurs.
        /// </summary>
        public TimeSpan MinimumPopulateDelay
        {
            get => GetValue(MinimumPopulateDelayProperty);
            set => SetValue(MinimumPopulateDelayProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="MaxDropDownHeight"/> property.
        /// </summary>
        public static readonly StyledProperty<double> MaxDropDownHeightProperty =
            AutoCompleteBox.MaxDropDownHeightProperty.AddOwner<DataGridAutoCompleteColumn>();

        /// <summary>
        /// Gets or sets the maximum height of the dropdown.
        /// </summary>
        public double MaxDropDownHeight
        {
            get => GetValue(MaxDropDownHeightProperty);
            set => SetValue(MaxDropDownHeightProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="IsTextCompletionEnabled"/> property.
        /// </summary>
        public static readonly StyledProperty<bool> IsTextCompletionEnabledProperty =
            AutoCompleteBox.IsTextCompletionEnabledProperty.AddOwner<DataGridAutoCompleteColumn>();

        /// <summary>
        /// Gets or sets whether text completion is enabled.
        /// </summary>
        public bool IsTextCompletionEnabled
        {
            get => GetValue(IsTextCompletionEnabledProperty);
            set => SetValue(IsTextCompletionEnabledProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="Watermark"/> property.
        /// </summary>
        public static readonly StyledProperty<string> WatermarkProperty =
            AutoCompleteBox.WatermarkProperty.AddOwner<DataGridAutoCompleteColumn>();

        /// <summary>
        /// Gets or sets the placeholder text displayed when the box is empty.
        /// </summary>
        public string Watermark
        {
            get => GetValue(WatermarkProperty);
            set => SetValue(WatermarkProperty, value);
        }

        static DataGridAutoCompleteColumn()
        {
            FilterModeProperty.OverrideDefaultValue<DataGridAutoCompleteColumn>(AutoCompleteFilterMode.Contains);
            MinimumPrefixLengthProperty.OverrideDefaultValue<DataGridAutoCompleteColumn>(1);
            MaxDropDownHeightProperty.OverrideDefaultValue<DataGridAutoCompleteColumn>(200);
        }

        /// <summary>
        /// Notifies the DataGrid when a property changes.
        /// </summary>
        protected override void OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
        {
            base.OnPropertyChanged(change);

            if (change.Property == ItemsSourceProperty
                || change.Property == ItemTemplateProperty
                || change.Property == FilterModeProperty
                || change.Property == MinimumPrefixLengthProperty
                || change.Property == MinimumPopulateDelayProperty
                || change.Property == MaxDropDownHeightProperty
                || change.Property == IsTextCompletionEnabledProperty
                || change.Property == WatermarkProperty)
            {
                NotifyPropertyChanged(change.Property.Name);
            }
        }

        /// <summary>
        /// Causes the column cell being edited to revert to the specified value.
        /// </summary>
        protected override void CancelCellEdit(Control editingElement, object uneditedValue)
        {
            if (editingElement is AutoCompleteBox autoComplete)
            {
                autoComplete.Text = uneditedValue as string ?? string.Empty;
            }
        }

        /// <summary>
        /// Creates the visual tree for read-only cells.
        /// </summary>
        protected override Control GenerateElement(DataGridCell cell, object dataItem)
        {
            var textBlock = new TextBlock
            {
                Name = "CellAutoCompleteTextBlock",
                VerticalAlignment = VerticalAlignment.Center
            };

            if (CellTextBlockTheme is { } theme)
            {
                textBlock.Theme = theme;
            }

            if (Binding != null && dataItem != DataGridCollectionView.NewItemPlaceholder)
            {
                textBlock.Bind(TextBlock.TextProperty, Binding);
            }

            return textBlock;
        }

        /// <summary>
        /// Creates the visual tree for editing cells.
        /// </summary>
        protected override Control GenerateEditingElementDirect(DataGridCell cell, object dataItem)
        {
            var autoComplete = new AutoCompleteBox
            {
                Name = "CellAutoCompleteBox",
                HorizontalAlignment = HorizontalAlignment.Stretch,
                VerticalAlignment = VerticalAlignment.Center
            };

            if (CellAutoCompleteTheme is { } theme)
            {
                autoComplete.Theme = theme;
            }

            SyncEditProperties(autoComplete);

            return autoComplete;
        }

        /// <summary>
        /// Called when a cell in the column enters editing mode.
        /// </summary>
        protected override object PrepareCellForEdit(Control editingElement, RoutedEventArgs editingEventArgs)
        {
            if (editingElement is AutoCompleteBox autoComplete)
            {
                string uneditedText = autoComplete.Text ?? string.Empty;

                // Select all text for easy replacement
                autoComplete.Focus();

                return uneditedText;
            }

            return string.Empty;
        }

        /// <summary>
        /// Called by the DataGrid control when this column asks for its elements to be updated.
        /// </summary>
        protected internal override void RefreshCellContent(Control element, string propertyName)
        {
            if (element == null)
            {
                throw new ArgumentNullException(nameof(element));
            }

            if (element is AutoCompleteBox autoComplete)
            {
                SyncEditProperties(autoComplete);
            }
            else
            {
                base.RefreshCellContent(element, propertyName);
            }
        }

        private void SyncEditProperties(AutoCompleteBox autoComplete)
        {
            if (ItemsSource != null)
            {
                autoComplete.ItemsSource = ItemsSource;
            }

            DataGridHelper.SyncColumnProperty(this, autoComplete, ItemTemplateProperty);
            autoComplete.FilterMode = FilterMode;
            autoComplete.MinimumPrefixLength = MinimumPrefixLength;
            autoComplete.MinimumPopulateDelay = MinimumPopulateDelay;
            autoComplete.MaxDropDownHeight = MaxDropDownHeight;
            autoComplete.IsTextCompletionEnabled = IsTextCompletionEnabled;

            if (!string.IsNullOrEmpty(Watermark))
            {
                autoComplete.Watermark = Watermark;
            }
        }

        private ControlTheme GetThemeValue(Lazy<ControlTheme> themeCache)
        {
            if (themeCache.IsValueCreated)
            {
                return themeCache.Value;
            }

            // Avoid permanently caching null before the column is attached to a grid.
            return OwningGrid == null ? null : themeCache.Value;
        }
    }
}
