// Copyright (c) Wiesław Šoltés. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

#nullable disable

using System;
using System.Globalization;
using Avalonia.Collections;
using Avalonia.Data;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Layout;
using Avalonia.Styling;

namespace Avalonia.Controls
{
    /// <summary>
    /// Represents a <see cref="DataGrid" /> column that hosts <see cref="MaskedTextBox" /> controls 
    /// for editing text values with input masks (e.g., phone numbers, SSN, credit cards).
    /// </summary>
#if !DATAGRID_INTERNAL
public
#else
internal
#endif
    class DataGridMaskedTextColumn : DataGridBoundColumn
    {
        private readonly Lazy<ControlTheme> _cellMaskedTextBoxTheme;
        private readonly Lazy<ControlTheme> _cellTextBlockTheme;

        /// <summary>
        /// Gets the theme applied to <see cref="MaskedTextBox" /> instances generated by the column.
        /// May return null when no matching resource is found.
        /// </summary>
        protected ControlTheme CellMaskedTextBoxTheme => GetThemeValue(_cellMaskedTextBoxTheme);

        /// <summary>
        /// Gets the theme applied to display <see cref="TextBlock" /> instances generated by the column.
        /// May return null when no matching resource is found.
        /// </summary>
        protected ControlTheme CellTextBlockTheme => GetThemeValue(_cellTextBlockTheme);

        /// <summary>
        /// Initializes a new instance of the <see cref="DataGridMaskedTextColumn"/> class.
        /// </summary>
        public DataGridMaskedTextColumn()
        {
            BindingTarget = MaskedTextBox.TextProperty;
            _cellMaskedTextBoxTheme = new Lazy<ControlTheme>(() => GetColumnControlTheme("DataGridCellMaskedTextBoxTheme"));
            _cellTextBlockTheme = new Lazy<ControlTheme>(() => GetColumnControlTheme("DataGridCellMaskedTextBlockTheme"));
        }

        /// <summary>
        /// Defines the <see cref="Mask"/> property.
        /// </summary>
        public static readonly StyledProperty<string> MaskProperty =
            MaskedTextBox.MaskProperty.AddOwner<DataGridMaskedTextColumn>();

        /// <summary>
        /// Gets or sets the mask format string.
        /// Common masks:
        /// - Phone: (000) 000-0000
        /// - SSN: 000-00-0000
        /// - Credit Card: 0000-0000-0000-0000
        /// - Postal Code: 00000-0000
        /// </summary>
        public string Mask
        {
            get => GetValue(MaskProperty);
            set => SetValue(MaskProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="PromptChar"/> property.
        /// </summary>
        public static readonly StyledProperty<char> PromptCharProperty =
            MaskedTextBox.PromptCharProperty.AddOwner<DataGridMaskedTextColumn>();

        /// <summary>
        /// Gets or sets the character used to represent unfilled positions.
        /// </summary>
        public char PromptChar
        {
            get => GetValue(PromptCharProperty);
            set => SetValue(PromptCharProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="AsciiOnly"/> property.
        /// </summary>
        public static readonly StyledProperty<bool> AsciiOnlyProperty =
            MaskedTextBox.AsciiOnlyProperty.AddOwner<DataGridMaskedTextColumn>();

        /// <summary>
        /// Gets or sets whether only ASCII characters are allowed.
        /// </summary>
        public bool AsciiOnly
        {
            get => GetValue(AsciiOnlyProperty);
            set => SetValue(AsciiOnlyProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="HidePromptOnLeave"/> property.
        /// </summary>
        public static readonly StyledProperty<bool> HidePromptOnLeaveProperty =
            MaskedTextBox.HidePromptOnLeaveProperty.AddOwner<DataGridMaskedTextColumn>();

        /// <summary>
        /// Gets or sets whether to hide prompt characters when the control loses focus.
        /// </summary>
        public bool HidePromptOnLeave
        {
            get => GetValue(HidePromptOnLeaveProperty);
            set => SetValue(HidePromptOnLeaveProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="ResetOnPrompt"/> property.
        /// </summary>
        public static readonly StyledProperty<bool> ResetOnPromptProperty =
            MaskedTextBox.ResetOnPromptProperty.AddOwner<DataGridMaskedTextColumn>();

        /// <summary>
        /// Gets or sets whether typing the prompt character resets the current position.
        /// </summary>
        public bool ResetOnPrompt
        {
            get => GetValue(ResetOnPromptProperty);
            set => SetValue(ResetOnPromptProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="ResetOnSpace"/> property.
        /// </summary>
        public static readonly StyledProperty<bool> ResetOnSpaceProperty =
            MaskedTextBox.ResetOnSpaceProperty.AddOwner<DataGridMaskedTextColumn>();

        /// <summary>
        /// Gets or sets whether typing space resets the current position.
        /// </summary>
        public bool ResetOnSpace
        {
            get => GetValue(ResetOnSpaceProperty);
            set => SetValue(ResetOnSpaceProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="Culture"/> property.
        /// </summary>
        public static readonly StyledProperty<CultureInfo> CultureProperty =
            MaskedTextBox.CultureProperty.AddOwner<DataGridMaskedTextColumn>();

        /// <summary>
        /// Gets or sets the culture used for parsing and formatting.
        /// </summary>
        public CultureInfo Culture
        {
            get => GetValue(CultureProperty);
            set => SetValue(CultureProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="Watermark"/> property.
        /// </summary>
        public static readonly StyledProperty<string> WatermarkProperty =
            AvaloniaProperty.Register<DataGridMaskedTextColumn, string>(nameof(Watermark));

        /// <summary>
        /// Gets or sets the placeholder text displayed when the box is empty.
        /// </summary>
        public string Watermark
        {
            get => GetValue(WatermarkProperty);
            set => SetValue(WatermarkProperty, value);
        }

        static DataGridMaskedTextColumn()
        {
            PromptCharProperty.OverrideDefaultValue<DataGridMaskedTextColumn>('_');
            HidePromptOnLeaveProperty.OverrideDefaultValue<DataGridMaskedTextColumn>(true);
        }

        /// <summary>
        /// Notifies the DataGrid when a property changes.
        /// </summary>
        protected override void OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
        {
            base.OnPropertyChanged(change);

            if (change.Property == MaskProperty
                || change.Property == PromptCharProperty
                || change.Property == AsciiOnlyProperty
                || change.Property == HidePromptOnLeaveProperty
                || change.Property == ResetOnPromptProperty
                || change.Property == ResetOnSpaceProperty
                || change.Property == CultureProperty
                || change.Property == WatermarkProperty)
            {
                NotifyPropertyChanged(change.Property.Name);
            }
        }

        /// <summary>
        /// Causes the column cell being edited to revert to the specified value.
        /// </summary>
        protected override void CancelCellEdit(Control editingElement, object uneditedValue)
        {
            if (editingElement is MaskedTextBox maskedTextBox)
            {
                maskedTextBox.Text = uneditedValue as string ?? string.Empty;
            }
        }

        /// <summary>
        /// Creates the visual tree for read-only cells.
        /// </summary>
        protected override Control GenerateElement(DataGridCell cell, object dataItem)
        {
            var textBlock = new TextBlock
            {
                Name = "CellMaskedTextBlock",
                VerticalAlignment = VerticalAlignment.Center
            };

            if (CellTextBlockTheme is { } theme)
            {
                textBlock.Theme = theme;
            }

            if (Binding != null && dataItem != DataGridCollectionView.NewItemPlaceholder)
            {
                textBlock.Bind(TextBlock.TextProperty, Binding);
            }

            return textBlock;
        }

        /// <summary>
        /// Creates the visual tree for editing cells.
        /// </summary>
        protected override Control GenerateEditingElementDirect(DataGridCell cell, object dataItem)
        {
            var maskedTextBox = new MaskedTextBox
            {
                Name = "CellMaskedTextBox",
                HorizontalAlignment = HorizontalAlignment.Stretch,
                VerticalAlignment = VerticalAlignment.Center
            };

            if (CellMaskedTextBoxTheme is { } theme)
            {
                maskedTextBox.Theme = theme;
            }

            SyncEditProperties(maskedTextBox);

            return maskedTextBox;
        }

        /// <summary>
        /// Called when a cell in the column enters editing mode.
        /// </summary>
        protected override object PrepareCellForEdit(Control editingElement, RoutedEventArgs editingEventArgs)
        {
            if (editingElement is MaskedTextBox maskedTextBox)
            {
                string uneditedText = maskedTextBox.Text ?? string.Empty;

                maskedTextBox.SelectAll();
                maskedTextBox.Focus();

                return uneditedText;
            }

            return string.Empty;
        }

        /// <summary>
        /// Called by the DataGrid control when this column asks for its elements to be updated.
        /// </summary>
        protected internal override void RefreshCellContent(Control element, string propertyName)
        {
            if (element == null)
            {
                throw new ArgumentNullException(nameof(element));
            }

            if (element is MaskedTextBox maskedTextBox)
            {
                SyncEditProperties(maskedTextBox);
            }
            else
            {
                base.RefreshCellContent(element, propertyName);
            }
        }

        private void SyncEditProperties(MaskedTextBox maskedTextBox)
        {
            if (!string.IsNullOrEmpty(Mask))
            {
                maskedTextBox.Mask = Mask;
            }

            maskedTextBox.PromptChar = PromptChar;
            maskedTextBox.AsciiOnly = AsciiOnly;
            maskedTextBox.HidePromptOnLeave = HidePromptOnLeave;
            maskedTextBox.ResetOnPrompt = ResetOnPrompt;
            maskedTextBox.ResetOnSpace = ResetOnSpace;

            if (Culture != null)
            {
                maskedTextBox.Culture = Culture;
            }

            if (!string.IsNullOrEmpty(Watermark))
            {
                maskedTextBox.Watermark = Watermark;
            }
        }

        private ControlTheme GetThemeValue(Lazy<ControlTheme> themeCache)
        {
            if (themeCache.IsValueCreated)
            {
                return themeCache.Value;
            }

            // Avoid permanently caching null before the column is attached to a grid.
            return OwningGrid == null ? null : themeCache.Value;
        }
    }
}
