// Copyright (c) Wiesław Šoltés. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

#nullable disable

using System;
using Avalonia.Collections;
using Avalonia.Data;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Layout;
using Avalonia.Styling;

namespace Avalonia.Controls
{
    /// <summary>
    /// Represents a <see cref="DataGrid" /> column that hosts <see cref="TimePicker" /> controls 
    /// for editing time values.
    /// </summary>
#if !DATAGRID_INTERNAL
public
#else
internal
#endif
    class DataGridTimePickerColumn : DataGridBoundColumn
    {
        private readonly Lazy<ControlTheme> _cellTimePickerTheme;
        private readonly Lazy<ControlTheme> _cellTextBlockTheme;

        /// <summary>
        /// Gets the theme applied to <see cref="TimePicker" /> instances generated by the column.
        /// May return null when no matching resource is found.
        /// </summary>
        protected ControlTheme CellTimePickerTheme => GetThemeValue(_cellTimePickerTheme);

        /// <summary>
        /// Gets the theme applied to display <see cref="TextBlock" /> instances generated by the column.
        /// May return null when no matching resource is found.
        /// </summary>
        protected ControlTheme CellTextBlockTheme => GetThemeValue(_cellTextBlockTheme);

        /// <summary>
        /// Initializes a new instance of the <see cref="DataGridTimePickerColumn"/> class.
        /// </summary>
        public DataGridTimePickerColumn()
        {
            BindingTarget = TimePicker.SelectedTimeProperty;
            _cellTimePickerTheme = new Lazy<ControlTheme>(() => GetColumnControlTheme("DataGridCellTimePickerTheme"));
            _cellTextBlockTheme = new Lazy<ControlTheme>(() => GetColumnControlTheme("DataGridCellTimeTextBlockTheme"));
        }

        /// <summary>
        /// Defines the <see cref="MinuteIncrement"/> property.
        /// </summary>
        public static readonly StyledProperty<int> MinuteIncrementProperty =
            TimePicker.MinuteIncrementProperty.AddOwner<DataGridTimePickerColumn>();

        /// <summary>
        /// Gets or sets the increment for minute selection.
        /// </summary>
        public int MinuteIncrement
        {
            get => GetValue(MinuteIncrementProperty);
            set => SetValue(MinuteIncrementProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="SecondIncrement"/> property.
        /// </summary>
        public static readonly StyledProperty<int> SecondIncrementProperty =
            TimePicker.SecondIncrementProperty.AddOwner<DataGridTimePickerColumn>();

        /// <summary>
        /// Gets or sets the increment for second selection.
        /// </summary>
        public int SecondIncrement
        {
            get => GetValue(SecondIncrementProperty);
            set => SetValue(SecondIncrementProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="ClockIdentifier"/> property.
        /// </summary>
        public static readonly StyledProperty<string> ClockIdentifierProperty =
            TimePicker.ClockIdentifierProperty.AddOwner<DataGridTimePickerColumn>();

        /// <summary>
        /// Gets or sets the clock format ("12HourClock" or "24HourClock").
        /// </summary>
        public string ClockIdentifier
        {
            get => GetValue(ClockIdentifierProperty);
            set => SetValue(ClockIdentifierProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="UseSeconds"/> property.
        /// </summary>
        public static readonly StyledProperty<bool> UseSecondsProperty =
            TimePicker.UseSecondsProperty.AddOwner<DataGridTimePickerColumn>();

        /// <summary>
        /// Gets or sets whether to show seconds.
        /// </summary>
        public bool UseSeconds
        {
            get => GetValue(UseSecondsProperty);
            set => SetValue(UseSecondsProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="FormatString"/> property.
        /// </summary>
        public static readonly StyledProperty<string> FormatStringProperty =
            AvaloniaProperty.Register<DataGridTimePickerColumn, string>(nameof(FormatString));

        /// <summary>
        /// Gets or sets the custom format string for display.
        /// </summary>
        public string FormatString
        {
            get => GetValue(FormatStringProperty);
            set => SetValue(FormatStringProperty, value);
        }

        static DataGridTimePickerColumn()
        {
            MinuteIncrementProperty.OverrideDefaultValue<DataGridTimePickerColumn>(1);
            SecondIncrementProperty.OverrideDefaultValue<DataGridTimePickerColumn>(1);
            ClockIdentifierProperty.OverrideDefaultValue<DataGridTimePickerColumn>("12HourClock");
            UseSecondsProperty.OverrideDefaultValue<DataGridTimePickerColumn>(false);
        }

        /// <summary>
        /// Notifies the DataGrid when a property changes.
        /// </summary>
        protected override void OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
        {
            base.OnPropertyChanged(change);

            if (change.Property == MinuteIncrementProperty
                || change.Property == SecondIncrementProperty
                || change.Property == ClockIdentifierProperty
                || change.Property == UseSecondsProperty
                || change.Property == FormatStringProperty)
            {
                NotifyPropertyChanged(change.Property.Name);
            }
        }

        /// <summary>
        /// Causes the column cell being edited to revert to the specified value.
        /// </summary>
        protected override void CancelCellEdit(Control editingElement, object uneditedValue)
        {
            if (editingElement is TimePicker timePicker)
            {
                timePicker.SelectedTime = uneditedValue as TimeSpan?;
            }
        }

        /// <summary>
        /// Creates the visual tree for read-only cells.
        /// </summary>
        protected override Control GenerateElement(DataGridCell cell, object dataItem)
        {
            var textBlock = new TextBlock
            {
                Name = "CellTimeTextBlock",
                VerticalAlignment = VerticalAlignment.Center
            };

            if (CellTextBlockTheme is { } theme)
            {
                textBlock.Theme = theme;
            }

            if (Binding != null && dataItem != DataGridCollectionView.NewItemPlaceholder)
            {
                // Create a binding with format string
                string formatString = GetTimeFormatString();
                
                if (Binding is Binding binding)
                {
                    var displayBinding = new Binding
                    {
                        Path = binding.Path,
                        Mode = BindingMode.OneWay,
                        StringFormat = formatString,
                        Converter = binding.Converter,
                        ConverterParameter = binding.ConverterParameter
                    };
                    textBlock.Bind(TextBlock.TextProperty, displayBinding);
                }
                else
                {
                    textBlock.Bind(TextBlock.TextProperty, Binding);
                }
            }

            return textBlock;
        }

        /// <summary>
        /// Creates the visual tree for editing cells.
        /// </summary>
        protected override Control GenerateEditingElementDirect(DataGridCell cell, object dataItem)
        {
            var timePicker = new TimePicker
            {
                Name = "CellTimePicker",
                HorizontalAlignment = HorizontalAlignment.Stretch,
                VerticalAlignment = VerticalAlignment.Center
            };

            if (CellTimePickerTheme is { } theme)
            {
                timePicker.Theme = theme;
            }

            SyncEditProperties(timePicker);

            return timePicker;
        }

        /// <summary>
        /// Called when a cell in the column enters editing mode.
        /// </summary>
        protected override object PrepareCellForEdit(Control editingElement, RoutedEventArgs editingEventArgs)
        {
            if (editingElement is TimePicker timePicker)
            {
                var uneditedValue = timePicker.SelectedTime;
                
                // Focus the time picker
                timePicker.Focus();

                return uneditedValue;
            }

            return null;
        }

        /// <summary>
        /// Called by the DataGrid control when this column asks for its elements to be updated.
        /// </summary>
        protected internal override void RefreshCellContent(Control element, string propertyName)
        {
            if (element == null)
            {
                throw new ArgumentNullException(nameof(element));
            }

            if (element is TimePicker timePicker)
            {
                SyncEditProperties(timePicker);
            }
            else
            {
                base.RefreshCellContent(element, propertyName);
            }
        }

        private string GetTimeFormatString()
        {
            if (!string.IsNullOrEmpty(FormatString))
            {
                return FormatString;
            }

            // Default format based on ClockIdentifier and UseSeconds
            bool is24Hour = ClockIdentifier == "24HourClock";
            
            if (UseSeconds)
            {
                return is24Hour ? @"hh\:mm\:ss" : "h:mm:ss tt";
            }
            else
            {
                return is24Hour ? @"hh\:mm" : "h:mm tt";
            }
        }

        private void SyncEditProperties(TimePicker timePicker)
        {
            timePicker.MinuteIncrement = MinuteIncrement;
            timePicker.SecondIncrement = SecondIncrement;
            timePicker.ClockIdentifier = ClockIdentifier;
            timePicker.UseSeconds = UseSeconds;
        }

        private ControlTheme GetThemeValue(Lazy<ControlTheme> themeCache)
        {
            if (themeCache.IsValueCreated)
            {
                return themeCache.Value;
            }

            // Avoid permanently caching null before the column is attached to a grid.
            return OwningGrid == null ? null : themeCache.Value;
        }
    }
}
