// Copyright (c) Wiesław Šoltés. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

#nullable disable

using System;
using Avalonia.Collections;
using Avalonia.Controls.Primitives;
using Avalonia.Data;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Layout;
using Avalonia.Styling;

namespace Avalonia.Controls
{
    /// <summary>
    /// Represents a <see cref="DataGrid" /> column that hosts <see cref="Slider" /> controls 
    /// for editing numeric values with a slider.
    /// </summary>
#if !DATAGRID_INTERNAL
public
#else
internal
#endif
    class DataGridSliderColumn : DataGridBoundColumn
    {
        private readonly Lazy<ControlTheme> _cellSliderTheme;
        private readonly Lazy<ControlTheme> _cellSliderDisplayTheme;

        /// <summary>
        /// Gets the theme applied to <see cref="Slider" /> instances generated by the column.
        /// May return null when no matching resource is found.
        /// </summary>
        protected ControlTheme CellSliderTheme => GetThemeValue(_cellSliderTheme);

        /// <summary>
        /// Gets the theme applied to display <see cref="Slider" /> instances generated by the column.
        /// May return null when no matching resource is found.
        /// </summary>
        protected ControlTheme CellSliderDisplayTheme => GetThemeValue(_cellSliderDisplayTheme);

        /// <summary>
        /// Initializes a new instance of the <see cref="DataGridSliderColumn"/> class.
        /// </summary>
        public DataGridSliderColumn()
        {
            BindingTarget = Slider.ValueProperty;
            _cellSliderTheme = new Lazy<ControlTheme>(() => GetColumnControlTheme("DataGridCellSliderTheme"));
            _cellSliderDisplayTheme = new Lazy<ControlTheme>(() => GetColumnControlTheme("DataGridCellSliderDisplayTheme"));
        }

        /// <summary>
        /// Defines the <see cref="Minimum"/> property.
        /// </summary>
        public static readonly StyledProperty<double> MinimumProperty =
            RangeBase.MinimumProperty.AddOwner<DataGridSliderColumn>();

        /// <summary>
        /// Gets or sets the minimum value.
        /// </summary>
        public double Minimum
        {
            get => GetValue(MinimumProperty);
            set => SetValue(MinimumProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="Maximum"/> property.
        /// </summary>
        public static readonly StyledProperty<double> MaximumProperty =
            RangeBase.MaximumProperty.AddOwner<DataGridSliderColumn>();

        /// <summary>
        /// Gets or sets the maximum value.
        /// </summary>
        public double Maximum
        {
            get => GetValue(MaximumProperty);
            set => SetValue(MaximumProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="SmallChange"/> property.
        /// </summary>
        public static readonly StyledProperty<double> SmallChangeProperty =
            RangeBase.SmallChangeProperty.AddOwner<DataGridSliderColumn>();

        /// <summary>
        /// Gets or sets the small change increment.
        /// </summary>
        public double SmallChange
        {
            get => GetValue(SmallChangeProperty);
            set => SetValue(SmallChangeProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="LargeChange"/> property.
        /// </summary>
        public static readonly StyledProperty<double> LargeChangeProperty =
            RangeBase.LargeChangeProperty.AddOwner<DataGridSliderColumn>();

        /// <summary>
        /// Gets or sets the large change increment.
        /// </summary>
        public double LargeChange
        {
            get => GetValue(LargeChangeProperty);
            set => SetValue(LargeChangeProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="TickFrequency"/> property.
        /// </summary>
        public static readonly StyledProperty<double> TickFrequencyProperty =
            Slider.TickFrequencyProperty.AddOwner<DataGridSliderColumn>();

        /// <summary>
        /// Gets or sets the tick frequency. 0 means no ticks.
        /// </summary>
        public double TickFrequency
        {
            get => GetValue(TickFrequencyProperty);
            set => SetValue(TickFrequencyProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="IsSnapToTickEnabled"/> property.
        /// </summary>
        public static readonly StyledProperty<bool> IsSnapToTickEnabledProperty =
            Slider.IsSnapToTickEnabledProperty.AddOwner<DataGridSliderColumn>();

        /// <summary>
        /// Gets or sets whether to snap to ticks.
        /// </summary>
        public bool IsSnapToTickEnabled
        {
            get => GetValue(IsSnapToTickEnabledProperty);
            set => SetValue(IsSnapToTickEnabledProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="TickPlacement"/> property.
        /// </summary>
        public static readonly StyledProperty<TickPlacement> TickPlacementProperty =
            Slider.TickPlacementProperty.AddOwner<DataGridSliderColumn>();

        /// <summary>
        /// Gets or sets the tick placement (None/TopLeft/BottomRight/Outside).
        /// </summary>
        public TickPlacement TickPlacement
        {
            get => GetValue(TickPlacementProperty);
            set => SetValue(TickPlacementProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="ShowValueText"/> property.
        /// </summary>
        public static readonly StyledProperty<bool> ShowValueTextProperty =
            AvaloniaProperty.Register<DataGridSliderColumn, bool>(nameof(ShowValueText), false);

        /// <summary>
        /// Gets or sets whether to show the current value as text.
        /// </summary>
        public bool ShowValueText
        {
            get => GetValue(ShowValueTextProperty);
            set => SetValue(ShowValueTextProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="ValueTextFormat"/> property.
        /// </summary>
        public static readonly StyledProperty<string> ValueTextFormatProperty =
            AvaloniaProperty.Register<DataGridSliderColumn, string>(nameof(ValueTextFormat), "N0");

        /// <summary>
        /// Gets or sets the format for value text display.
        /// </summary>
        public string ValueTextFormat
        {
            get => GetValue(ValueTextFormatProperty);
            set => SetValue(ValueTextFormatProperty, value);
        }

        static DataGridSliderColumn()
        {
            MinimumProperty.OverrideDefaultValue<DataGridSliderColumn>(0);
            MaximumProperty.OverrideDefaultValue<DataGridSliderColumn>(100);
            SmallChangeProperty.OverrideDefaultValue<DataGridSliderColumn>(1);
            LargeChangeProperty.OverrideDefaultValue<DataGridSliderColumn>(10);
            TickPlacementProperty.OverrideDefaultValue<DataGridSliderColumn>(TickPlacement.None);
        }

        /// <summary>
        /// Notifies the DataGrid when a property changes.
        /// </summary>
        protected override void OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
        {
            base.OnPropertyChanged(change);

            if (change.Property == MinimumProperty
                || change.Property == MaximumProperty
                || change.Property == SmallChangeProperty
                || change.Property == LargeChangeProperty
                || change.Property == TickFrequencyProperty
                || change.Property == IsSnapToTickEnabledProperty
                || change.Property == TickPlacementProperty
                || change.Property == ShowValueTextProperty
                || change.Property == ValueTextFormatProperty)
            {
                NotifyPropertyChanged(change.Property.Name);
            }
        }

        /// <summary>
        /// Causes the column cell being edited to revert to the specified value.
        /// </summary>
        protected override void CancelCellEdit(Control editingElement, object uneditedValue)
        {
            if (editingElement is Slider slider && uneditedValue is double value)
            {
                slider.Value = value;
            }
        }

        /// <summary>
        /// Creates the visual tree for read-only cells.
        /// </summary>
        protected override Control GenerateElement(DataGridCell cell, object dataItem)
        {
            if (ShowValueText)
            {
                // Show text representation instead of slider for display
                var textBlock = new TextBlock
                {
                    Name = "CellSliderValueText",
                    VerticalAlignment = VerticalAlignment.Center,
                    HorizontalAlignment = HorizontalAlignment.Center
                };

                if (Binding != null && dataItem != DataGridCollectionView.NewItemPlaceholder)
                {
                    if (Binding is Binding binding)
                    {
                        var displayBinding = new Binding
                        {
                            Path = binding.Path,
                            Mode = BindingMode.OneWay,
                            StringFormat = ValueTextFormat,
                            Converter = binding.Converter,
                            ConverterParameter = binding.ConverterParameter
                        };
                        textBlock.Bind(TextBlock.TextProperty, displayBinding);
                    }
                    else
                    {
                        textBlock.Bind(TextBlock.TextProperty, Binding);
                    }
                }

                return textBlock;
            }

            var slider = new Slider
            {
                Name = "CellSliderDisplay",
                Orientation = Orientation.Horizontal,
                IsHitTestVisible = false,
                Focusable = false
            };

            if (CellSliderDisplayTheme is { } theme)
            {
                slider.Theme = theme;
            }

            SyncSliderProperties(slider);

            if (Binding != null && dataItem != DataGridCollectionView.NewItemPlaceholder)
            {
                slider.Bind(Slider.ValueProperty, Binding);
            }

            return slider;
        }

        /// <summary>
        /// Creates the visual tree for editing cells.
        /// </summary>
        protected override Control GenerateEditingElementDirect(DataGridCell cell, object dataItem)
        {
            var slider = new Slider
            {
                Name = "CellSlider",
                Orientation = Orientation.Horizontal
            };

            if (CellSliderTheme is { } theme)
            {
                slider.Theme = theme;
            }

            SyncSliderProperties(slider);

            return slider;
        }

        /// <summary>
        /// Called when a cell in the column enters editing mode.
        /// </summary>
        protected override object PrepareCellForEdit(Control editingElement, RoutedEventArgs editingEventArgs)
        {
            if (editingElement is Slider slider)
            {
                var uneditedValue = slider.Value;
                slider.Focus();
                return uneditedValue;
            }

            return 0.0;
        }

        /// <summary>
        /// Called by the DataGrid control when this column asks for its elements to be updated.
        /// </summary>
        protected internal override void RefreshCellContent(Control element, string propertyName)
        {
            if (element == null)
            {
                throw new ArgumentNullException(nameof(element));
            }

            if (element is Slider slider)
            {
                SyncSliderProperties(slider);
            }
            else
            {
                base.RefreshCellContent(element, propertyName);
            }
        }

        private void SyncSliderProperties(Slider slider)
        {
            slider.Minimum = Minimum;
            slider.Maximum = Maximum;
            slider.SmallChange = SmallChange;
            slider.LargeChange = LargeChange;
            slider.TickFrequency = TickFrequency;
            slider.IsSnapToTickEnabled = IsSnapToTickEnabled;
            slider.TickPlacement = TickPlacement;
        }

        private ControlTheme GetThemeValue(Lazy<ControlTheme> themeCache)
        {
            if (themeCache.IsValueCreated)
            {
                return themeCache.Value;
            }

            // Avoid permanently caching null before the column is attached to a grid.
            return OwningGrid == null ? null : themeCache.Value;
        }
    }
}
