// Copyright (c) Wiesław Šoltés. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

#nullable disable

using System;
using Avalonia.Collections;
using Avalonia.Data;
using Avalonia.Interactivity;
using Avalonia.Layout;
using Avalonia.Media;
using Avalonia.Media.Imaging;
using Avalonia.Styling;

namespace Avalonia.Controls
{
    /// <summary>
    /// Represents a <see cref="DataGrid" /> column that hosts <see cref="Image" /> controls 
    /// for displaying images. This column is read-only by default.
    /// </summary>
#if !DATAGRID_INTERNAL
public
#else
internal
#endif
    class DataGridImageColumn : DataGridBoundColumn
    {
        private readonly Lazy<ControlTheme> _cellTextBoxTheme;

        /// <summary>
        /// Gets the theme applied to editing <see cref="TextBox" /> instances generated by the column.
        /// May return null when no matching resource is found.
        /// </summary>
        protected ControlTheme CellTextBoxTheme => GetThemeValue(_cellTextBoxTheme);

        /// <summary>
        /// Initializes a new instance of the <see cref="DataGridImageColumn"/> class.
        /// </summary>
        public DataGridImageColumn()
        {
            BindingTarget = Image.SourceProperty;
            _cellTextBoxTheme = new Lazy<ControlTheme>(() => GetColumnControlTheme("DataGridCellTextBoxTheme"));
        }

        /// <summary>
        /// Defines the <see cref="ImageWidth"/> property.
        /// </summary>
        public static readonly StyledProperty<double> ImageWidthProperty =
            AvaloniaProperty.Register<DataGridImageColumn, double>(nameof(ImageWidth), double.NaN);

        /// <summary>
        /// Gets or sets the image width.
        /// </summary>
        public double ImageWidth
        {
            get => GetValue(ImageWidthProperty);
            set => SetValue(ImageWidthProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="ImageHeight"/> property.
        /// </summary>
        public static readonly StyledProperty<double> ImageHeightProperty =
            AvaloniaProperty.Register<DataGridImageColumn, double>(nameof(ImageHeight), double.NaN);

        /// <summary>
        /// Gets or sets the image height.
        /// </summary>
        public double ImageHeight
        {
            get => GetValue(ImageHeightProperty);
            set => SetValue(ImageHeightProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="Stretch"/> property.
        /// </summary>
        public static readonly StyledProperty<Stretch> StretchProperty =
            Image.StretchProperty.AddOwner<DataGridImageColumn>();

        /// <summary>
        /// Gets or sets the image stretch mode.
        /// </summary>
        public Stretch Stretch
        {
            get => GetValue(StretchProperty);
            set => SetValue(StretchProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="StretchDirection"/> property.
        /// </summary>
        public static readonly StyledProperty<StretchDirection> StretchDirectionProperty =
            Image.StretchDirectionProperty.AddOwner<DataGridImageColumn>();

        /// <summary>
        /// Gets or sets the image stretch direction.
        /// </summary>
        public StretchDirection StretchDirection
        {
            get => GetValue(StretchDirectionProperty);
            set => SetValue(StretchDirectionProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="AllowEditing"/> property.
        /// </summary>
        public static readonly StyledProperty<bool> AllowEditingProperty =
            AvaloniaProperty.Register<DataGridImageColumn, bool>(nameof(AllowEditing), false);

        /// <summary>
        /// Gets or sets whether editing is allowed (edit the image source path).
        /// </summary>
        public bool AllowEditing
        {
            get => GetValue(AllowEditingProperty);
            set => SetValue(AllowEditingProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="Watermark"/> property.
        /// </summary>
        public static readonly StyledProperty<string> WatermarkProperty =
            TextBox.WatermarkProperty.AddOwner<DataGridImageColumn>();

        /// <summary>
        /// Gets or sets the placeholder text displayed when the box is empty.
        /// </summary>
        public string Watermark
        {
            get => GetValue(WatermarkProperty);
            set => SetValue(WatermarkProperty, value);
        }

        static DataGridImageColumn()
        {
            StretchProperty.OverrideDefaultValue<DataGridImageColumn>(Stretch.Uniform);
            StretchDirectionProperty.OverrideDefaultValue<DataGridImageColumn>(StretchDirection.Both);
        }

        /// <summary>
        /// Gets or sets whether this column is read-only.
        /// </summary>
        public override bool IsReadOnly
        {
            get => !AllowEditing || base.IsReadOnly;
            set => base.IsReadOnly = value;
        }

        /// <summary>
        /// Notifies the DataGrid when a property changes.
        /// </summary>
        protected override void OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
        {
            base.OnPropertyChanged(change);

            if (change.Property == ImageWidthProperty
                || change.Property == ImageHeightProperty
                || change.Property == StretchProperty
                || change.Property == StretchDirectionProperty
                || change.Property == AllowEditingProperty
                || change.Property == WatermarkProperty)
            {
                NotifyPropertyChanged(change.Property.Name);
            }
        }

        /// <summary>
        /// Causes the column cell being edited to revert to the specified value.
        /// </summary>
        protected override void CancelCellEdit(Control editingElement, object uneditedValue)
        {
            if (editingElement is TextBox textBox)
            {
                textBox.Text = uneditedValue as string ?? string.Empty;
            }
        }

        /// <summary>
        /// Creates the visual tree for cells.
        /// </summary>
        protected override Control GenerateElement(DataGridCell cell, object dataItem)
        {
            var image = new Image
            {
                Name = "CellImage",
                VerticalAlignment = VerticalAlignment.Center,
                HorizontalAlignment = HorizontalAlignment.Center
            };

            SyncImageProperties(image);

            if (Binding != null && dataItem != DataGridCollectionView.NewItemPlaceholder)
            {
                image.Bind(Image.SourceProperty, Binding);
            }

            return image;
        }

        /// <summary>
        /// Creates the visual tree for editing cells.
        /// </summary>
        protected override Control GenerateEditingElementDirect(DataGridCell cell, object dataItem)
        {
            if (!AllowEditing)
            {
                return GenerateElement(cell, dataItem);
            }

            // Allow editing the image path/URL as text
            var textBox = new TextBox
            {
                Name = "CellImageTextBox"
            };

            if (CellTextBoxTheme is { } theme)
            {
                textBox.Theme = theme;
            }

            SyncEditingProperties(textBox);

            return textBox;
        }

        /// <summary>
        /// Called when a cell in the column enters editing mode.
        /// </summary>
        protected override object PrepareCellForEdit(Control editingElement, RoutedEventArgs editingEventArgs)
        {
            if (editingElement is TextBox textBox)
            {
                string uneditedText = textBox.Text ?? string.Empty;
                textBox.SelectAll();
                textBox.Focus();
                return uneditedText;
            }

            return string.Empty;
        }

        /// <summary>
        /// Called by the DataGrid control when this column asks for its elements to be updated.
        /// </summary>
        protected internal override void RefreshCellContent(Control element, string propertyName)
        {
            if (element == null)
            {
                throw new ArgumentNullException(nameof(element));
            }

            if (element is Image image)
            {
                SyncImageProperties(image);
            }
            else if (element is TextBox textBox && propertyName == nameof(Watermark))
            {
                SyncEditingProperties(textBox);
            }
            else
            {
                base.RefreshCellContent(element, propertyName);
            }
        }

        private void SyncImageProperties(Image image)
        {
            if (!double.IsNaN(ImageWidth))
            {
                image.Width = ImageWidth;
            }

            if (!double.IsNaN(ImageHeight))
            {
                image.Height = ImageHeight;
            }

            image.Stretch = Stretch;
            image.StretchDirection = StretchDirection;
        }

        private void SyncEditingProperties(TextBox textBox)
        {
            if (!string.IsNullOrEmpty(Watermark))
            {
                textBox.Watermark = Watermark;
            }
        }

        private ControlTheme GetThemeValue(Lazy<ControlTheme> themeCache)
        {
            if (themeCache.IsValueCreated)
            {
                return themeCache.Value;
            }

            // Avoid permanently caching null before the column is attached to a grid.
            return OwningGrid == null ? null : themeCache.Value;
        }
    }
}
